name: ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        severity: warning

    - name: Verify executables
      run: |
        if [ ! -x "./executable_yolo" ]; then
          echo "Error: executable_yolo is not executable"
          exit 1
        fi
        if [ ! -x "./install.sh" ]; then
          echo "Error: install.sh is not executable"
          exit 1
        fi
        if [ ! -x "./test.sh" ]; then
          echo "Error: test.sh is not executable"
          exit 1
        fi
        echo "All scripts are executable"
