name: ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'
        severity: warning
        
    - name: Verify scripts are executable
      run: |
        test -x executable_yolo || (echo "executable_yolo is not executable" && exit 1)
        test -x install.sh || (echo "install.sh is not executable" && exit 1)
