name: ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@2.0.0
      with:
        check_together: 'yes'
        severity: warning
        
    - name: Verify scripts are executable
      run: |
        test -x executable_yolo || (echo "executable_yolo is not executable" && exit 1)
        test -x install.sh || (echo "install.sh is not executable" && exit 1)
        test -x tests/test_flags.sh || (echo "tests/test_flags.sh is not executable" && exit 1)
        test -x tests/test_worktree.sh || (echo "tests/test_worktree.sh is not executable" && exit 1)
        
    - name: Test yolo help
      run: |
        ./executable_yolo --help
        ./executable_yolo --version
        
    - name: Run flag tests
      run: |
        ./tests/test_flags.sh
        
    - name: Run worktree tests
      run: |
        ./tests/test_worktree.sh
