name: ShellCheck

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Run ShellCheck
      run: |
        shellcheck --severity=warning executable_yolo install.sh test.sh

    - name: Verify scripts are executable
      run: |
        test -x executable_yolo || (echo "executable_yolo is not executable" && exit 1)
        test -x install.sh || (echo "install.sh is not executable" && exit 1)
        test -x test.sh || (echo "test.sh is not executable" && exit 1)