name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get install -y git
        
    - name: Run tests
      run: |
        export PATH="$(pwd)/mocks:$PATH"
        ./test.sh
