name: Update Vibe Coded Badge

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip vibe-badge]')"

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: trieloff/vibe-coded-badge-action@main
